services:

  collector:
    image: otel/opentelemetry-collector-contrib
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:cached
    env_file:
      - .env
    ports:
      - 4317:4317 # App -> Collector

  seq:
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    ports:
      - 8080:80

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 16686:16686

  zipkin:
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - 9411:9411

  grafana:
    image: grafana/otel-lgtm
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

  aspire:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    restart: unless-stopped
    ports:
      - 18888:18888
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

# Traces are ephemeral.
# Logs and metrics are persisted.
volumes:
  seq-data:
  grafana-data:
